added self.last_clicked_roi = "" because i keep getting this error AttributeError: 'SpectrumViewerWindowView' object has no attribute 'last_clicked_roi'